Added kubecontext parameter for create ns with WI and install helm release
masmovil/bazel-rules pull request #26
Opened 2021-05-27 11:47 UTC by tomich87

Allow set kubecontext to migration to dev-02 gke cluster.

2021-05-27 14:13 UTC, chrissgyulev commented on k8s/k8s-namespace.bzl
> +      kubecontext = "gke_mm-k8s-dev-01_europe-west1_mm-k8s-dev-01"
This part is a little bit crappy

2021-05-27 15:04 UTC, tomich87 commented on k8s/k8s-namespace.bzl
> +      kubecontext = "gke_mm-k8s-dev-01_europe-west1_mm-k8s-dev-01"
solved

2021-05-27 15:12 UTC, chrissgyulev approved these changes
LGTM

2021-05-27 15:29 UTC, danigar commented on examples/base-package/BUILD
> +  kubernetes_context = "gke_mm-k8s-dev-02_europe-west2_mm-k8s-dev-02"
Maybe we should use other context name in these examples?

2021-05-27 15:30 UTC, danigar commented on helm/helm-release.bzl
> +      "kubernetes_context": attr.string(mandatory = False, default = "gke_mm-k8s-dev-01_europe-west1_mm-k8s-dev-01"),
Same here. Or make this mandatory maybe?

2021-05-27 15:31 UTC, danigar requested changes
Minnor comments. We should add this new flags to the docs -> README.md

2021-05-27 15:32 UTC, danigar commented
@gutmox the rule works well without this new parameters as it takes the default kube context of the jenkins node. If you are changing the cluster in the kubecontext (in the CI), should be enough.

2021-05-28 11:39 UTC, danigar requested changes
just add some doc to the readme.md, but everythingelse 👌

2021-05-28 13:07 UTC, merged